#!/usr/bin/env bash
echo "list objects"
if [ -z "$1" ]; then
    echo "there needs to be a bucket name e.g. ./bucket my bucket-name"
    exit 1
fi

BUCKET_NAME=$1
echo "LIST OBJECTS"
aws s3api list-objects-v2 \
--bucket $BUCKET_NAME