#!/usr/bin/env bash

echo "put-object"
#check for a bucket name
if [ -z "$1" ]; then
    echo "there needs to be a bucket name e.g. ./bucket my bucket-name"
    exit 1
fi
#check for a filename 
if [ -z "$2" ]; then
    echo "there needs to be a filename prefix e.g. ./bucket my bucket-name my filename-prefix"
    exit 1
fi